export const SET_GENERACIONES = "SET_GENERACIONES";
export const SET_POKEMONES = "SET_POKEMONES";
export const SET_POKEMON_SELECCIONADO = "SET_POKEMON_SELECCIONADO";
export const SET_GENERACION_SELECCIONADA = "SET_GENERACION_SELECCIONADA";